version: "3"
services:
  node:
    build: ""
    command: "npm run start"
    working_dir: "/home/node/app"
    environment:
      - NODE-ENV = "production"
      - PORT = "3300"
    expose:
      - "3300"
    ports:
      - "3300:3300"

  db:
    container_name: node_postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_rural
    volumes:
      - ./data:/data/postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: developer@developer.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 8080:80
