version: '3'
services:
  node:
    build: ''
    command: 'npm run start'
    working_dir: '/home/node/app'
    environment:
      - NODE-ENV='production'
      - PORT='3300'
    expose:
      - '3300'
    ports:
      - '3300:3300'
    networks:
      - my-network

  db:
    container_name: node_postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_rural
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: developer@developer.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 8080:80
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
